#!/usr/bin/env bash
# PreToolUse (Write|Edit|NotebookEdit): block edits that break the playbook's "Never" rules.
# Exit 2 = block; stderr is shown to Claude.
f=$(jq -r '.tool_input.file_path // empty')
[ -z "$f" ] && exit 0

deny() { echo "Blocked: $1" >&2; exit 2; }
base=$(basename "$f")

# Secrets: .env and variants, but .env.example is documentation and stays editable.
case "$base" in
  .env.example) ;;
  .env|.env.*) deny "$base holds secrets and must never be edited or committed by Claude (playbook §10). Edit .env.example instead." ;;
esac

# Lock files are produced by uv/pnpm, never by hand.
case "$base" in
  uv.lock|pnpm-lock.yaml|package-lock.json|yarn.lock|poetry.lock)
    deny "$base is generated by the package manager. Run uv/pnpm instead of editing it." ;;
esac

# Applied migrations are immutable: creating a new revision is fine, changing an existing one is not.
case "$f" in
  */alembic/versions/*)
    [ -e "$f" ] && deny "existing Alembic migration $base must not change. Add a new revision instead." ;;
esac

# Golden eval set is fixed (playbook §8.1). New files may be added; existing ones may not change.
case "$f" in
  */data/golden/*)
    [ -e "$f" ] && deny "$base is part of the golden eval set, which must stay fixed. Ask the user before changing it." ;;
esac

exit 0
